export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 5,
      sourceType: "script",
      globals: {
        jQuery: "readonly",
        agentclerk: "readonly",
        agentclerkStripe: "readonly",
        window: "readonly",
        document: "readonly",
        console: "readonly",
        alert: "readonly",
        confirm: "readonly",
        location: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        Stripe: "readonly",
        JSON: "readonly",
        agentclerkWidget: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-unreachable": "error",
      "no-constant-condition": "warn",
      "no-empty": "warn",
    },
  },
];
